### ISSUE TITLE
Sidekick still shows up as original role in scoreboard

### ISSUE THREAD

**Issue by cuteexe** [Alf21/ttt2-role_siki#14]
When you shoot a Traitor using your sidekick deagle. he will still show as traitor on the scoreboard to his old traitor teammates. same goes for jester if you shoot a jester he will still show as jester to all traitors. 

did you maybe forget SendFullStateUpdate() ?

**Comment by TimGoll** [comment]
This is intended. The traitor should not know that his teammate is no longer his teammate

**Comment by cuteexe** [comment]
alright will tell that to my players
