### ISSUE TITLE
Sidekick is put on the Traitor Team if the Jackal is Killed under Sidekick Mode 2 (Sidekick receives targets)

### ISSUE THREAD

**Issue by AaronMcKenney** [Alf21/ttt2-role_siki#19]
If the sidekick mode is 2, the Sidekick does not become a Jackal if they are killed, but instead receives targets which they can kill for credits. However, if the Jackal is killed in this mode, the Sidekick appears to switch to the Traitor's side. This is pretty strange in my eyes. I originally added the Jackal to the server because it was a cool 3rd party group, but its ability to one-hit convert players to its team combined with the Sidekick's swaying loyalties makes it a bit OP. Under sidekick mode 1 the Jackal can convert multiple people to its team through strategic deaths, and under sidekick mode 2 the Sidekick can switch to the traitor's team, which often gives too much of an advantage to the traitors.

Can it be changed so that if the Jackal is killed, the Sidekick instead becomes a Jackal, but does not receive a Sidekick Gun (under sidekick mode 2)?

**Comment by TimGoll** [comment]
He switches to the traitor team?

**Comment by AaronMcKenney** [comment]
Yes. I've had a game where only one traitor and one sidekick are left, and the traitor team wins. Thinking about this a bit more, it is possible that the sidekick was technically on their own team still, but lost the ability to win (similar to what happens if there's only a traitor and a jester left)? I'm not sure what the point of that would be though, as in our games it just leads to the sidekick RDM-ing.

**Comment by TimGoll** [comment]
AH, yes, this is known since a while. The sidekick alone can't win. Thanks for reminding us.
